// Code generated by "stringer -type=AddrType"; DO NOT EDIT.

package raft

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AddrTypeUnkown - -1]
	_ = x[AddrTypeLocal-1]
	_ = x[AddrTypeClient-2]
	_ = x[AddrTypePeer-3]
	_ = x[AddrTypePeers-4]
}

const (
	_AddrType_name_0 = "AddrTypeUnkown"
	_AddrType_name_1 = "AddrTypeLocalAddrTypeClientAddrTypePeerAddrTypePeers"
)

var (
	_AddrType_index_1 = [...]uint8{0, 13, 27, 39, 52}
)

func (i AddrType) String() string {
	switch {
	case i == -1:
		return _AddrType_name_0
	case 1 <= i && i <= 4:
		i -= 1
		return _AddrType_name_1[_AddrType_index_1[i]:_AddrType_index_1[i+1]]
	default:
		return "AddrType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
