// Code generated by "stringer -type=AddrType -linecomment"; DO NOT EDIT.

package raft

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AddrTypeLocal-0]
	_ = x[AddrTypeClient-1]
	_ = x[AddrTypePeer-2]
	_ = x[AddrTypePeers-3]
}

const _AddrType_name = "AddrLocalAddrClientAddrPeerAddrPeers"

var _AddrType_index = [...]uint8{0, 9, 19, 27, 36}

func (i AddrType) String() string {
	if i < 0 || i >= AddrType(len(_AddrType_index)-1) {
		return "AddrType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AddrType_name[_AddrType_index[i]:_AddrType_index[i+1]]
}
