// generate.go

package raft

//func generateType(typeName string) {

//    header = `
//// Code generated by "stringer -type=AddrType"; DO NOT EDIT.

//package raft
//    `

//    template := `

//func (a *AddrLocal) Type() AddrType {
//    return AddrTypeLocal
//}
//    `

//    body := fmt.Sprintf(template, strings.ToLower(f.methodType), f.VarParam(), f.name, f.VarParamValue(), returnBody, setVar, url, makeIt(f.returnType), f.name, returnRef)

//}
