// Code generated by "stringer -type=MsgEventType -linecomment"; DO NOT EDIT.

package raft

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventTypeUnkown - -1]
	_ = x[EventTypeHeartbeatReq-1]
	_ = x[EventTypeHeartbeatResp-2]
	_ = x[EventTypeClientReq-3]
	_ = x[EventTypeClientResp-4]
	_ = x[EventTypeVoteReq-5]
	_ = x[EventTypeVoteResp-6]
	_ = x[EventTypeAppendEntriesReq-7]
	_ = x[EventTypeAcceptEntriesResp-8]
	_ = x[EventTypeRefuseEntriesResp-9]
	_ = x[EventTypeInstallSnapReq-10]
}

const (
	_MsgEventType_name_0 = "EventUknown"
	_MsgEventType_name_1 = "EventHeartbeatReqEventHeartbeatResponseEventClientReqEventClientResponseEventVoteReqEventVoteResponseEventAppendEntriesReqEventAcceptEntriesResponseEventRefuseEntriesResponseEventInstallSnapshot"
)

var (
	_MsgEventType_index_1 = [...]uint8{0, 17, 39, 53, 72, 84, 101, 122, 148, 174, 194}
)

func (i MsgEventType) String() string {
	switch {
	case i == -1:
		return _MsgEventType_name_0
	case 1 <= i && i <= 10:
		i -= 1
		return _MsgEventType_name_1[_MsgEventType_index_1[i]:_MsgEventType_index_1[i+1]]
	default:
		return "MsgEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
