// Code generated by "stringer -type=ReqType,RespType -linecomment"; DO NOT EDIT.

package raft

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReqTypeQuery-0]
	_ = x[ReqTypeMutate-1]
	_ = x[ReqTypeStatus-2]
}

const _ReqType_name = "ReqQueryReqMutateReqStatus"

var _ReqType_index = [...]uint8{0, 8, 17, 26}

func (i ReqType) String() string {
	if i < 0 || i >= ReqType(len(_ReqType_index)-1) {
		return "ReqType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReqType_name[_ReqType_index[i]:_ReqType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RespTypeStatus-3]
	_ = x[RespTypeState-4]
}

const _RespType_name = "RespStatusRespState"

var _RespType_index = [...]uint8{0, 10, 19}

func (i RespType) String() string {
	i -= 3
	if i < 0 || i >= RespType(len(_RespType_index)-1) {
		return "RespType(" + strconv.FormatInt(int64(i+3), 10) + ")"
	}
	return _RespType_name[_RespType_index[i]:_RespType_index[i+1]]
}
